name: Update Letterboxd Featured Movie

on:
  schedule:
    - cron: "0 0 * * 1"  # Every Monday
  workflow_dispatch:

concurrency:
  group: letterboxd-readme
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo with full history and push access
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true  # Required for git push

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: pip install feedparser beautifulsoup4

      # 4️⃣ Run your Python script to update README
      - name: Run Letterboxd script
        run: python scripts/letterboxd_readme_widget.py

      # 5️⃣ Commit and push changes safely
      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git diff-index --quiet HEAD || git commit -m "Update Letterboxd Featured Movie section"
          # Force push safely with lease
          git push origin HEAD:master --force-with-lease